version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"    # Port pour les connexions AMQP
      - "15672:15672"  # Port pour l'interface de gestion (si activ√©e)
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root


#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=db_Mobile_App'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#      - 'MONGO_INITDB_ROOT_PASSWORD=root'
#
#    ports:
#      - '27017:27017'
#
#    volumes:
#      - './db_Mobile_Data:/data/db'


